apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jellyfin.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "jellyfin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jellyfin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "jellyfin.name" . }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8096
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JELLYFIN_CACHE_DIR
              value: /config
            - name: JELLYFIN_CONFIG_DIR
              value: /config/cache
          volumeMounts:
            - mountPath: /config
              name: {{ include "jellyfin.name" . }}-data
            - mountPath: /config/transcodes
              name: {{ include "jellyfin.name" . }}-transcodes
            - mountPath: /data/media
              name: {{ include "jellyfin.name" . }}-media
              readOnly: True
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      restartPolicy: Always
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "jellyfin.name" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.name" . }}-data
        - name: {{ include "jellyfin.name" . }}-transcodes
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.name" . }}-transcodes
        - name: {{ include "jellyfin.name" . }}-media
          persistentVolumeClaim:
            claimName: {{ include "jellyfin.name" . }}-media
