apiVersion: v1
kind: Service
metadata:
  name: {{ include "jellyfin.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8096
      protocol: TCP
      name: http
  selector:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
