apiVersion: v2
name: jellyfin
description: Jellyfin - Free Software Media System
type: application
version: 1.0.0
appVersion: "10.8.10"
kubeVersion: ">=1.12.0"
keywords:
  - jellyfin
  - media server
home: https://github.com/jrmileham/charts
sources:
 - https://github.com/jellyfin/jellyfin